services:
  mysql:
    image: mysql:8.0
    container_name: music-review-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gsu
      MYSQL_USER: musicuser
      MYSQL_PASSWORD: musicpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: music-review-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=musicuser
      - DB_PASSWORD=musicpass
      - DB_NAME=gsu
      - DB_PORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
